Repository torrust/torrust-index, pull requests merged in 2023-06, with the labels that each got.

#170 Documentation: statistics importer console command
  src/console/commands/import_tracker_statistics.rs
  src/lib.rs
  src/tracker/statistics_importer.rs
Labels: documentation, enhancement

#171 App upgrader documentation
  src/lib.rs
  src/upgrades/from_v1_0_0_to_v2_0_0/upgrader.rs
Labels: documentation, enhancement

#184 New config option for log level
  config-idx-back.local.toml
  config.local.toml
  src/app.rs
  src/bootstrap/logging.rs
  src/config.rs
  src/console/commands/import_tracker_statistics.rs
  tests/environments/isolated.rs
Labels: refactoring

#185 Axum API: `about` context
  src/web/api/v1/contexts/about/handlers.rs
  src/web/api/v1/contexts/about/routes.rs
  tests/e2e/contexts/about/contract.rs
Labels: refactoring

#162 76 add tags to torrents
  migrations/mysql/20230321122049_torrust_torrent_tags.sql
  migrations/mysql/20230321122825_torrust_torrent_tag_links.sql
  migrations/sqlite3/20230321122049_torrust_torrent_tags.sql
  migrations/sqlite3/20230321122825_torrust_torrent_tag_links.sql
  src/app.rs
  src/common.rs
  src/databases/database.rs
  src/databases/mysql.rs
  src/databases/sqlite.rs
  src/errors.rs
  src/models/mod.rs
  src/models/response.rs
  src/models/torrent_tag.rs
  src/routes/mod.rs
  src/routes/tag.rs
  src/routes/torrent.rs
  src/services/authentication.rs
  src/services/torrent.rs
Labels: needs rebase

#191 Refactor API: extract `tag` service
  src/app.rs
  src/common.rs
  src/databases/database.rs
  src/databases/mysql.rs
  src/databases/sqlite.rs
  src/errors.rs
  src/routes/tag.rs
  src/services/category.rs
  src/services/mod.rs
  src/services/tag.rs
  src/services/torrent.rs
  tests/common/client.rs
  tests/common/contexts/mod.rs
  tests/common/contexts/tag/fixtures.rs
  tests/common/contexts/tag/forms.rs
  tests/common/contexts/tag/mod.rs
  tests/common/contexts/tag/responses.rs
  tests/e2e/contexts/mod.rs
  tests/e2e/contexts/tag/contract.rs
  tests/e2e/contexts/tag/mod.rs
  tests/e2e/contexts/tag/steps.rs
Labels: refactoring

#193 Fix SQL error in SQLite
  src/databases/sqlite.rs
Labels: bug

#196 Axum API: `user` context
  .github/workflows/develop.yml
  Cargo.lock
  Cargo.toml
  src/auth.rs
  src/config.rs
  src/errors.rs
  src/routes/category.rs
  src/routes/proxy.rs
  src/routes/settings.rs
  src/routes/tag.rs
  src/routes/torrent.rs
  src/routes/user.rs
  src/services/user.rs
  src/web/api/v1/auth.rs
  src/web/api/v1/contexts/about/routes.rs
  src/web/api/v1/contexts/user/forms.rs
  src/web/api/v1/contexts/user/handlers.rs
  src/web/api/v1/contexts/user/mod.rs
  src/web/api/v1/contexts/user/responses.rs
  src/web/api/v1/contexts/user/routes.rs
  src/web/api/v1/extractors/bearer_token.rs
  src/web/api/v1/extractors/mod.rs
  src/web/api/v1/mod.rs
  src/web/api/v1/responses.rs
  src/web/api/v1/routes.rs
  tests/common/contexts/user/asserts.rs
  tests/common/contexts/user/fixtures.rs
  tests/common/contexts/user/mod.rs
  tests/common/contexts/user/responses.rs
  tests/e2e/config.rs
  tests/e2e/contexts/user/contract.rs
  tests/e2e/contexts/user/steps.rs
Labels: refactoring

#195 Axum API: `category` context
  src/web/api/v1/contexts/category/forms.rs
  src/web/api/v1/contexts/category/handlers.rs
  src/web/api/v1/contexts/category/mod.rs
  src/web/api/v1/contexts/category/responses.rs
  src/web/api/v1/contexts/category/routes.rs
  src/web/api/v1/routes.rs
  tests/common/contexts/category/asserts.rs
  tests/common/contexts/category/mod.rs
  tests/common/contexts/category/responses.rs
  tests/e2e/contexts/category/contract.rs
  tests/e2e/contexts/category/steps.rs
  tests/e2e/contexts/user/steps.rs
Labels: refactoring

#199 Axum API: `root` enpoints
  src/web/api/v1/routes.rs
  tests/e2e/contexts/root/contract.rs
Labels: refactoring

#200 Axum API: `tag` context
  src/web/api/v1/contexts/mod.rs
  src/web/api/v1/contexts/tag/forms.rs
  src/web/api/v1/contexts/tag/handlers.rs
  src/web/api/v1/contexts/tag/mod.rs
  src/web/api/v1/contexts/tag/responses.rs
  src/web/api/v1/contexts/tag/routes.rs
  src/web/api/v1/routes.rs
  tests/common/contexts/tag/asserts.rs
  tests/common/contexts/tag/mod.rs
  tests/common/contexts/tag/responses.rs
  tests/e2e/contexts/tag/contract.rs
Labels: refactoring

#201 Axum API: `settings` context
  src/web/api/v1/contexts/settings/handlers.rs
  src/web/api/v1/contexts/settings/mod.rs
  src/web/api/v1/contexts/settings/routes.rs
  src/web/api/v1/routes.rs
  tests/e2e/contexts/settings/contract.rs
Labels: refactoring

#202 Axum API: `torrent` context
  Cargo.lock
  Cargo.toml
  src/auth.rs
  src/errors.rs
  src/web/api/v1/contexts/category/handlers.rs
  src/web/api/v1/contexts/category/responses.rs
  src/web/api/v1/contexts/settings/handlers.rs
  src/web/api/v1/contexts/tag/handlers.rs
  src/web/api/v1/contexts/tag/responses.rs
  src/web/api/v1/contexts/torrent/forms.rs
  src/web/api/v1/contexts/torrent/handlers.rs
  src/web/api/v1/contexts/torrent/mod.rs
  src/web/api/v1/contexts/torrent/responses.rs
  src/web/api/v1/contexts/torrent/routes.rs
  src/web/api/v1/contexts/user/handlers.rs
  src/web/api/v1/contexts/user/responses.rs
  src/web/api/v1/responses.rs
  src/web/api/v1/routes.rs
  tests/common/asserts.rs
  tests/common/contexts/category/asserts.rs
  tests/common/contexts/tag/asserts.rs
  tests/common/contexts/user/asserts.rs
  tests/e2e/contexts/category/contract.rs
  tests/e2e/contexts/settings/contract.rs
  tests/e2e/contexts/tag/contract.rs
  tests/e2e/contexts/torrent/contract.rs
Labels: refactoring

#205 Axum API: `proxy` context
  src/web/api/v1/contexts/proxy/handlers.rs
  src/web/api/v1/contexts/proxy/mod.rs
  src/web/api/v1/contexts/proxy/responses.rs
  src/web/api/v1/contexts/proxy/routes.rs
  src/web/api/v1/routes.rs
  tests/e2e/contexts/mod.rs
  tests/e2e/contexts/proxy/contract.rs
  tests/e2e/contexts/proxy/mod.rs
Labels: refactoring
