Repository torrust/torrust-index, pull requests merged in 2023-11, with the labels that each got.

#367 chore: bump serde_json to 1.0.108
  Cargo.lock
Labels: Dependencies, Needs Rebase, Build | Project System

#393 Refactor: extract duplicate function `wait_for_container_to_be_healthy`
  contrib/dev-tools/container/e2e/mysql/run-e2e-tests.sh
  contrib/dev-tools/container/e2e/sqlite/run-e2e-tests.sh
  contrib/dev-tools/container/functions/wait_for_container_to_be_healthy.sh
Labels: Continuous Integration, Code Cleanup / Refactoring, - Developer -

#395 Implement health check for the Index container
  Containerfile
  contrib/dev-tools/container/e2e/mysql/run-e2e-tests.sh
  contrib/dev-tools/container/e2e/sqlite/run-e2e-tests.sh
  share/default/config/index.container.mysql.toml
  share/default/config/index.container.sqlite3.toml
  share/default/config/index.development.sqlite3.toml
  src/app.rs
  src/bin/health_check.rs
  src/config.rs
  src/console/mod.rs
  src/console/tracker_statistics_importer.rs
  src/lib.rs
  src/web/api/v1/contexts/settings/mod.rs
  src/web/api/v1/routes.rs
  tests/common/contexts/settings/mod.rs
  tests/environments/isolated.rs
Labels: Continuous Integration, - Developer -, Quality & Assurance

#411 Add script to setup DB for development
  contrib/dev-tools/init/install-local.sh
Labels: - Developer -
