Repository torrust/torrust-index, pull requests merged in 2023-05, with the labels that each got.

#134 feat: [#91] added image proxy with cache
  .gitignore
  Cargo.lock
  Cargo.toml
  src/app.rs
  src/cache/cache.rs
  src/cache/image/manager.rs
  src/cache/image/mod.rs
  src/cache/mod.rs
  src/common.rs
  src/config.rs
  src/errors.rs
  src/lib.rs
  src/routes/mod.rs
  src/routes/proxy.rs
  src/tracker.rs
Labels: needs-rebase

#138 Refactor configuration
  .dockerignore
  config-idx-back.local.toml
  config-tracker.local.toml
  docker/README.md
  docker/bin/e2e-env-up.sh
  src/bootstrap/config.rs
  src/routes/settings.rs
  tests/common/client.rs
  tests/common/contexts/settings/form.rs
  tests/common/contexts/settings/mod.rs
  tests/e2e/config.rs
  tests/e2e/contexts/settings/contract.rs
  tests/e2e/contexts/user/contract.rs
  tests/e2e/environment.rs
  tests/e2e/mod.rs
  tests/environments/app_starter.rs
  tests/environments/isolated.rs
  tests/environments/shared.rs
Labels: refactoring

#139 Fix deprecate chrono function warning
  src/auth.rs
  src/databases/mysql.rs
  src/databases/sqlite.rs
  src/mailer.rs
  src/routes/user.rs
  src/upgrades/from_v1_0_0_to_v2_0_0/databases/sqlite_v2_0_0.rs
  src/utils/clock.rs
  src/utils/mod.rs
  src/utils/time.rs
Labels: tidying

#160 Decouple services from actix-web
  src/app.rs
  src/auth.rs
  src/common.rs
  src/config.rs
  src/databases/database.rs
  src/databases/mysql.rs
  src/databases/sqlite.rs
  src/errors.rs
  src/lib.rs
  src/mailer.rs
  src/models/category.rs
  src/models/mod.rs
  src/models/response.rs
  src/models/torrent.rs
  src/models/torrent_file.rs
  src/models/user.rs
  src/routes/about.rs
  src/routes/category.rs
  src/routes/proxy.rs
  src/routes/settings.rs
  src/routes/torrent.rs
  src/routes/user.rs
  src/services/about.rs
  src/services/authentication.rs
  src/services/category.rs
  src/services/mod.rs
  src/services/proxy.rs
  src/services/settings.rs
  src/services/torrent.rs
  src/services/user.rs
  src/tracker/service.rs
  src/ui/mod.rs
  src/ui/proxy.rs
  templates/verify.html
Labels: refactoring

#165 API documentation on docs.rs
  docs/media/mandelbrot_2048x2048_infohash_v1.png.torrent
  docs/media/mandelbrot_2048x2048_infohash_v1.png.torrent.json
  project-words.txt
  src/cache/image/manager.rs
  src/lib.rs
  src/web/api/mod.rs
  src/web/api/v1/auth.rs
  src/web/api/v1/contexts/about/mod.rs
  src/web/api/v1/contexts/category/mod.rs
  src/web/api/v1/contexts/mod.rs
  src/web/api/v1/contexts/proxy/mod.rs
  src/web/api/v1/contexts/settings/mod.rs
  src/web/api/v1/contexts/torrent/mod.rs
  src/web/api/v1/contexts/user/mod.rs
  src/web/api/v1/mod.rs
  src/web/mod.rs
Labels: documentation
