Repository torrust/torrust-index, pull requests merged in 2024-07, with the labels that each got.

#649 Update dependencies
  .github/workflows/container.yaml
  Cargo.lock
Labels: Dependencies

#656 Configuration overhaul: add `version` to the configuration
  share/default/config/index.container.mysql.toml
  share/default/config/index.container.sqlite3.toml
  share/default/config/index.development.sqlite3.toml
  share/default/config/index.private.e2e.container.sqlite3.toml
  share/default/config/index.public.e2e.container.mysql.toml
  share/default/config/index.public.e2e.container.sqlite3.toml
  src/config/mod.rs
  src/config/v2/api.rs
  src/config/v2/auth.rs
  src/config/v2/database.rs
  src/config/v2/image_cache.rs
  src/config/v2/logging.rs
  src/config/v2/mail.rs
  src/config/v2/mod.rs
  src/config/v2/net.rs
  src/config/v2/tracker.rs
  src/config/v2/tracker_statistics_importer.rs
  src/config/v2/website.rs
  src/web/api/client/v1/contexts/settings/mod.rs
Labels: Enhancement / Feature Request

#658 Configuration overhaul: print the final configuration to console
  src/app.rs
  src/bootstrap/logging.rs
  src/config/mod.rs
  src/config/v2/mod.rs
  src/console/commands/seeder/logging.rs
Labels: Enhancement / Feature Request

#659 Configuration overhaul: rename `log_level` to `threshold`
  share/default/config/index.container.mysql.toml
  share/default/config/index.container.sqlite3.toml
  share/default/config/index.development.sqlite3.toml
  share/default/config/index.private.e2e.container.sqlite3.toml
  share/default/config/index.public.e2e.container.mysql.toml
  share/default/config/index.public.e2e.container.sqlite3.toml
  src/app.rs
  src/bootstrap/logging.rs
  src/config/mod.rs
  src/config/v2/logging.rs
  src/console/commands/tracker_statistics_importer/app.rs
  tests/common/contexts/settings/mod.rs
  tests/environments/isolated.rs
Labels: Enhancement / Feature Request

#660 Update dependencies
  Cargo.lock
Labels: Dependencies

#624 #615 Use Casbin for the authorization layer
  Cargo.lock
  Cargo.toml
  src/app.rs
  src/services/authorization.rs
  src/services/torrent.rs
  src/services/user.rs
Labels: Needs Rebase

#671 Update dependencies
  Cargo.lock
Labels: Dependencies

#686 fix: [#580] E2E tests failing with MySQL
  contrib/dev-tools/container/e2e/mysql/run-e2e-tests.sh
  tests/environments/shared.rs
Labels: Continuous Integration, Testing
