Repository torrust/torrust-index, pull requests merged in 2024-06, with the labels that each got.

#617 Update dependencies
  Cargo.lock
Labels: Dependencies

#614 448 move authorization logic to new layer
  Cargo.lock
  Cargo.toml
  src/app.rs
  src/common.rs
  src/services/authentication.rs
  src/services/authorization.rs
  src/services/category.rs
  src/services/mod.rs
  src/services/proxy.rs
  src/services/settings.rs
  src/services/tag.rs
  src/services/torrent.rs
  src/services/user.rs
Labels: Needs Rebase

#619 New API endpoint to change the users' password
  src/app.rs
  src/common.rs
  src/databases/database.rs
  src/databases/mysql.rs
  src/databases/sqlite.rs
  src/errors.rs
  src/services/authentication.rs
  src/services/user.rs
  src/web/api/server/v1/contexts/user/forms.rs
  src/web/api/server/v1/contexts/user/handlers.rs
  src/web/api/server/v1/contexts/user/routes.rs
  tests/common/client.rs
  tests/common/contexts/user/asserts.rs
  tests/common/contexts/user/fixtures.rs
  tests/common/contexts/user/forms.rs
  tests/e2e/web/api/v1/contexts/user/contract.rs
Labels: Enhancement / Feature Request

#623 Move from `log` to `tracing` crate
  Cargo.lock
  Cargo.toml
  packages/located-error/Cargo.toml
  packages/located-error/src/lib.rs
  src/bootstrap/logging.rs
  src/console/commands/seeder/api.rs
  src/console/commands/seeder/app.rs
  src/console/commands/seeder/logging.rs
  src/console/cronjobs/tracker_statistics_importer.rs
  src/databases/mysql.rs
  src/databases/sqlite.rs
  src/mailer.rs
  src/models/torrent_file.rs
  src/services/torrent.rs
  src/services/user.rs
  src/tracker/service.rs
  src/tracker/statistics_importer.rs
  src/web/api/server/mod.rs
  src/web/api/server/signals.rs
  src/web/api/server/v1/contexts/torrent/handlers.rs
  tests/environments/app_starter.rs
Labels: Enhancement / Feature Request

#625 Update dependencies
  Cargo.lock
Labels: Dependencies

#631 Configuration overhaul: version 2 for the configuration toml file (breaking changes)
  share/default/config/index.container.mysql.toml
  share/default/config/index.container.sqlite3.toml
  share/default/config/index.development.sqlite3.toml
  share/default/config/index.private.e2e.container.sqlite3.toml
  share/default/config/index.public.e2e.container.mysql.toml
  share/default/config/index.public.e2e.container.sqlite3.toml
  src/app.rs
  src/bootstrap/logging.rs
  src/config/mod.rs
  src/config/v1/api.rs
  src/config/v1/auth.rs
  src/config/v1/image_cache.rs
  src/config/v1/logging.rs
  src/config/v1/mail.rs
  src/config/v1/mod.rs
  src/config/v1/net.rs
  src/config/v1/tracker.rs
  src/config/v1/tracker_statistics_importer.rs
  src/console/commands/tracker_statistics_importer/app.rs
  src/lib.rs
  src/mailer.rs
  src/services/user.rs
  src/web/api/client/v1/contexts/settings/mod.rs
  src/web/api/mod.rs
  src/web/api/server/mod.rs
  src/web/api/server/v1/contexts/settings/mod.rs
  src/web/api/server/v1/contexts/user/mod.rs
  tests/common/contexts/settings/mod.rs
  tests/e2e/environment.rs
  tests/environments/isolated.rs
Labels: Enhancement / Feature Request

#632 Update dependencies
  Cargo.lock
Labels: Dependencies

#639 Update dependencies
  Cargo.lock
Labels: Dependencies

#640 Update tracker config
  .env.local
  compose.yaml
  contrib/dev-tools/container/e2e/mysql/e2e-env-up.sh
  contrib/dev-tools/container/e2e/sqlite/mode/private/e2e-env-up.sh
  contrib/dev-tools/container/e2e/sqlite/mode/public/e2e-env-up.sh
Labels: Dependencies
