Repository torrust/torrust-index, pull requests merged in 2024-05, with the labels that each got.

#568 Udpate dependencies
  Cargo.lock
Labels: Dependencies

#577 Rename tracker env vars
  .env.local
  Containerfile
  compose.yaml
  contrib/dev-tools/container/e2e/mysql/e2e-env-down.sh
  contrib/dev-tools/container/e2e/mysql/e2e-env-up.sh
  contrib/dev-tools/container/e2e/sqlite/e2e-env-down.sh
  contrib/dev-tools/container/e2e/sqlite/e2e-env-up.sh
  share/default/config/tracker.container.mysql.toml
  share/default/config/tracker.container.sqlite3.toml
  share/default/config/tracker.e2e.container.sqlite3.toml
  src/config.rs
Labels: Code Cleanup / Refactoring

#578 Update dependencies
  Cargo.lock
Labels: Dependencies

#579 Fix errors in scripts
  contrib/dev-tools/container/e2e/mysql/e2e-env-down.sh
  contrib/dev-tools/container/e2e/mysql/run-e2e-tests.sh
  contrib/dev-tools/container/e2e/sqlite/e2e-env-down.sh
  contrib/dev-tools/container/e2e/sqlite/e2e-env-up.sh
  contrib/dev-tools/container/e2e/sqlite/run-e2e-tests.sh
  contrib/dev-tools/init/install-local.sh
Labels: Bug, Continuous Integration

#584 TSL support
  Cargo.lock
  Cargo.toml
  project-words.txt
  share/default/config/index.development.sqlite3.toml
  share/tls/localhost.crt
  share/tls/localhost.key
  src/app.rs
  src/config.rs
  src/main.rs
  src/web/api/mod.rs
  src/web/api/server/custom_axum.rs
  src/web/api/server/mod.rs
  src/web/api/server/signals.rs
  tests/environments/app_starter.rs
Labels: Enhancement / Feature Request

#588 Add some tests to configuration before refactoring
  src/config.rs
Labels: Testing

#592 Configuration overhaul: migrate to Figment crate
  Cargo.lock
  Cargo.toml
  src/app.rs
  src/config/mod.rs
  src/config/v1/mod.rs
  src/config/v1/tracker.rs
  src/config/validator.rs
  src/services/settings.rs
  src/utils/parse_torrent.rs
  src/web/api/client/v1/contexts/settings/mod.rs
  src/web/api/server/v1/contexts/settings/mod.rs
  tests/common/client.rs
  tests/common/contexts/settings/mod.rs
  tests/environments/app_starter.rs
  tests/environments/isolated.rs
  tests/environments/shared.rs
Labels: Code Cleanup / Refactoring

#597 Update dependencies
  Cargo.lock
Labels: Dependencies

#598 Configuration overhaul: rename env vars
  .env.local
  Containerfile
  README.md
  compose.yaml
  contrib/dev-tools/container/e2e/mysql/e2e-env-down.sh
  contrib/dev-tools/container/e2e/mysql/e2e-env-up.sh
  contrib/dev-tools/container/e2e/mysql/run-e2e-tests.sh
  contrib/dev-tools/container/e2e/sqlite/e2e-env-down.sh
  contrib/dev-tools/container/e2e/sqlite/e2e-env-up.sh
  contrib/dev-tools/container/e2e/sqlite/run-e2e-tests.sh
  contrib/dev-tools/container/run.sh
  docs/containers.md
  share/default/config/index.container.mysql.toml
  share/default/config/index.container.sqlite3.toml
  share/default/config/index.e2e.container.mysql.toml
  share/default/config/index.e2e.container.sqlite3.toml
  src/bootstrap/config.rs
  src/config/mod.rs
  src/lib.rs
  tests/e2e/config.rs
Labels: Code Cleanup / Refactoring

#602 Fix new linting errors
  src/console/commands/tracker_statistics_importer/app.rs
  src/lib.rs
  src/upgrades/from_v1_0_0_to_v2_0_0/upgrader.rs
  src/utils/parse_torrent.rs
  tests/e2e/mod.rs
Labels: Code Cleanup / Refactoring

#604 Configuration overhaul: define default values and remove default values from config file templates
  share/default/config/index.container.mysql.toml
  share/default/config/index.container.sqlite3.toml
  share/default/config/index.development.sqlite3.toml
  share/default/config/index.e2e.container.mysql.toml
  share/default/config/index.e2e.container.sqlite3.toml
  src/config/v1/api.rs
  src/config/v1/auth.rs
  src/config/v1/database.rs
  src/config/v1/image_cache.rs
  src/config/v1/mail.rs
  src/config/v1/mod.rs
  src/config/v1/net.rs
  src/config/v1/tracker.rs
  src/config/v1/tracker_statistics_importer.rs
  src/config/v1/website.rs
Labels: Enhancement / Feature Request

#609 update dependencies
  Cargo.lock
Labels: Dependencies
