Repository torrust/torrust-index, pull requests merged in 2024-03, with the labels that each got.

#513 BEP 17. Persist metainfo field `httpseeds`
  migrations/mysql/20240304104106_torrust_add_http_seeds_to_torrent.sql
  migrations/sqlite3/20240304104106_torrust_add_http_seeds_to_torrent.sql
  src/databases/database.rs
  src/databases/mysql.rs
  src/databases/sqlite.rs
  src/models/torrent_file.rs
Labels: Enhancement / Feature Request, - User -

#515 BEP 5. Persist metainfo field `nodes`
  migrations/mysql/20240304165035_torrust_add_nodes_to_torrent.sql
  migrations/sqlite3/20240304165035_torrust_add_nodes_to_torrent.sql
  share/default/config/index.development.sqlite3.toml
  src/databases/database.rs
  src/databases/mysql.rs
  src/databases/sqlite.rs
  src/models/torrent_file.rs
Labels: Enhancement / Feature Request, - User -

#516 Refactor BEP 30 implmentation
  migrations/mysql/20240305110750_torrust_bep_rename_root_hash_to_is_bep_30.sql
  migrations/mysql/20240305120015_torrust_add_independent_root_hash_field.sql
  migrations/sqlite3/20240305110750_torrust_bep_rename_root_hash_to_is_bep_30.sql
  migrations/sqlite3/20240305120015_torrust_add_independent_root_hash_field.sql
  src/databases/mysql.rs
  src/databases/sqlite.rs
  src/models/torrent_file.rs
  src/services/torrent_file.rs
  src/upgrades/from_v1_0_0_to_v2_0_0/databases/sqlite_v2_0_0.rs
  tests/upgrades/from_v1_0_0_to_v2_0_0/transferrer_testers/torrent_transferrer_tester.rs
Labels: - Developer -

#519 Refactor error handling for torrent upload
  src/errors.rs
  src/services/torrent.rs
  tests/e2e/web/api/v1/contexts/torrent/contract.rs
Labels: - User -

#522 Refactor: rename fields in upload torrent response
  src/services/torrent.rs
  src/web/api/server/v1/contexts/torrent/responses.rs
  tests/common/contexts/torrent/responses.rs
  tests/e2e/web/api/v1/contexts/torrent/contract.rs
  tests/e2e/web/api/v1/contexts/torrent/steps.rs
Labels: Enhancement / Feature Request, - Developer -

#530 Improve tracker statistics importation
  migrations/mysql/20240312130530_torrust_add_update_data_to_tracker_stats.sql
  migrations/sqlite3/20240312130530_torrust_add_update_data_to_tracker_stats.sql
  src/console/cronjobs/tracker_statistics_importer.rs
  src/databases/database.rs
  src/databases/mysql.rs
  src/databases/sqlite.rs
  src/tracker/api.rs
  src/tracker/service.rs
  src/tracker/statistics_importer.rs
  src/utils/clock.rs
Labels: Enhancement / Feature Request

#537 Update dependencies
  Cargo.lock
  Cargo.toml
  src/upgrades/from_v1_0_0_to_v2_0_0/databases/sqlite_v2_0_0.rs
  src/utils/clock.rs
Labels: Dependencies
